# Generated by Django 6.0.4 on 2026-05-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lareserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
