# Generated by Django 6.0.4 on 2026-05-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lareserve", "0002_reservation_table_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="special_requests",
            field=models.TextField(blank=True, null=True),
        ),
    ]
