# Generated by Django 6.0.5 on 2026-05-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lareserve", "0003_reservation_special_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="table_id",
            field=models.CharField(max_length=255),
        ),
    ]
