# Generated by Django 6.0.4 on 2026-06-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lareserve', '0004_reservation_guest_email_reservation_guest_name_and_more'),
        ('lareserve', '0004_reservation_table_id_charfield'),
    ]

    operations = [
    ]
