# Generated by Django 6.0.4 on 2026-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lareserve', '0005_merge_20260602_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished'), ('ACCEPTED', 'Accepted')], default='CONFIRMED', max_length=20),
        ),
    ]
